// contstants - info about my lists
export const movieLists = [
  {
    slug: 'unhinged-women',
    title: 'Unhinged Women Who Self Destruct',
    description: 'and we love them for it',
    color: '#2d2d2d',
    video: '/blackSwan.mp4',
    brightness: 'brightness-80',
    films: [
      { title: 'Black Swan', year: 2010 },
      { title: 'Gone Girl', year: 2014 },
      { title: 'Girl, Interrupted', year: 1999 },
      { title: 'Antichrist', year: 2009 },
      { title: 'Nymphomaniac', year: 2014 },
      { title: 'Swallow', year: 2019 },
      { title: 'Thirteen', year: 2003 },
      { title: 'The Neon Demon', year: 2016 },
      { title: 'Shiva Baby', year: 2020 },
      { title: 'Frances Ha', year: 2012 },
      { title: 'Young Adult', year: 2011 },
      { title: 'Mulholland Drive', year: 2001 },
      { title: 'The Piano Teacher', year: 2001 },
      { title: 'Babygirl', year: 2024 },
      { title: 'The Worst Person in the World', year: 2021 },
      { title: 'Melancholia', year: 2011 },
      { title: 'Gia', year: 1998 },
      { title: 'Chloe', year: 2010 },
      { title: 'Secretary', year: 2002 },
      { title: 'The Virgin Suicides', year: 1999 },
      { title: 'May December', year: 2023 },
      { title: 'Bottoms', year: 2023 },
      { title: 'Poor Things', year: 2023 },
      { title: 'Beef', year: 2023 },
      { title: 'Daisy Jones & The Six', year: 2023 },
      { title: 'Sick of Myself', year: 2022 },
      { title: 'Blue Jasmine', year: 2013 },
      { title: 'Tully', year: 2018 },
      { title: 'Stoker', year: 2013 },
      { title: 'Challengers', year: 2024 },
      { title: 'I, Tonya', year: 2017 },
      { title: 'The dreamers', year: 2003 },
      { title: 'Marie Antoinette', year: 2006 },
      { title: 'Licorice Pizza', year: 2021 },
      { title: 'Vicky Cristina Barcelona', year: 2008 },
      { title: 'Young & Beautiful', year: 2013 },
    ],
  },
  {
    slug: 'unusual-animation',
    title: 'Unusual animation',
    description: 'something beyond disney',
    color: '#252525',
    video: '/persipolis.mp4',
    brightness: 'brightness-50',
    films: [
      { title: 'The Willoughbys', year: 2020 },
      { title: 'Fantastic Mr. Fox', year: 2009 },
      { title: 'Ruben Brandt, Collector', year: 2018 },
      { title: 'The Breadwinner', year: 2017 },
      { title: 'Coraline', year: 2009 },
      { title: 'Isle of Dogs', year: 2018 },
      { title: 'Waltz with Bashir', year: 2008 },
      { title: 'The House', year: 2022 },
      { title: 'The Suicide Shop', year: 2012 },
      { title: 'Where Is Anne Frank', year: 2021 },
      { title: 'The Iron Giant', year: 1999 },
      { title: 'The Nightmare Before Christmas', year: 1993 },
      { title: 'James and the Giant Peach', year: 1996 },
      { title: 'Over the Garden Wall', year: 2014 },
      { title: 'Missing Link', year: 2019 },
      { title: 'Wolfwalkers', year: 2020 },
      { title: 'Flee', year: 2021 },
      { title: 'Guillermo del Toro’s Pinocchio', year: 2022 },
      { title: 'It’s Such a Beautiful Day', year: 2012 },
      { title: 'Klaus', year: 2019 },
      { title: 'Corpse Bride', year: 2005 },
      { title: 'Persepolis', year: 2007 },
      { title: 'The Wind Rises', year: 2013 },
      { title: 'The Boxtrolls', year: 2014 },
      { title: 'Your Name.', year: 2016 },
      { title: 'Ping Pong the Animation', year: 2014 },
      { title: 'My Life as a Zucchini', year: 2016 },
      { title: 'The Secret of Kells', year: 2009 },
      { title: '9', year: 2009 },
      { title: 'Ernest & Celestine', year: 2012 },
      { title: 'The Polar Express', year: 2004 },
      { title: 'ParaNorman', year: 2012 },
      { title: 'Nocturna', year: 2007 },
      { title: 'Mary and Max', year: 2009 },
      { title: 'Loving Vincent', year: 2017 },
      { title: 'Kubo and the Two Strings', year: 2016 },
      { title: 'Wolf Children', year: 2012 },
      { title: 'Anomalisa', year: 2015 },
      { title: 'Tekkonkinkreet', year: 2006 },
      { title: 'Song of the Sea', year: 2014 },
      { title: 'Scott Pilgrim Takes Off', year: 2023 },
    ],
  },
  {
    slug: 'manic-pixie',
    title: 'Manic Pixie Dream Girling',
    description: 'delusional? maybe. iconic? absolutely.',
    color: '#181818',
    video: '/submarine.mp4',
    brightness: 'brightness-80',
    films: [
      { title: '500 Days of Summer', year: 2009 },
      { title: 'Almost Famous', year: 2000 },
      { title: 'Eternal Sunshine of the Spotless Mind', year: 2004 },
      { title: 'Scott Pilgrim vs. the World', year: 2010 },
      { title: 'Ruby Sparks', year: 2012 },
      { title: 'Amélie', year: 2001 },
      { title: 'Paper Towns', year: 2015 },
      { title: 'Me and Earl and the Dying Girl', year: 2015 },
      { title: 'An Education', year: 2009 },
      { title: 'Kate & Leopold', year: 2001 },
      { title: 'Her', year: 2013 },
      { title: 'Breakfast at Tiffany’s', year: 1961 },
      { title: 'Annie Hall', year: 1977 },
      { title: 'Yes Man', year: 2008 },
      { title: 'Liberal Arts', year: 2012 },
      { title: 'Submarine', year: 2010 },
      { title: 'Moonrise Kingdom', year: 2012 },
      { title: 'The Art of Getting By', year: 2011 },
      { title: 'The Perks of Being a Wallflower', year: 2012 },
      { title: 'The Science of Sleep', year: 2006 },
      { title: 'The Dreamers', year: 2003 },
      { title: 'Lars and the Real Girl', year: 2007 },
      { title: 'Begin Again', year: 2013 },
      { title: 'Frances Ha', year: 2012 },
    ],
  },
  {
    slug: 'favourites',
    title: 'Personal favourites',
    description: 'handpicked. heart-approved.',
    color: '#0e0e0e',
    video: '/breakfast.mp4',
    brightness: 'brightness-80',
    films: [
      { title: 'Nymphomaniac', year: 2014 },
      { title: 'Split', year: 2016 },
      { title: 'Me and Earl and the Dying Girl', year: 2015 },
      { title: 'Birdman or (The Unexpected Virtue of Ignorance)', year: 2014 },
      { title: 'Les Misérables', year: 2012 },
      { title: 'Anna Karenina', year: 2012 },
      { title: 'Heartbeats', year: 2010 },
      { title: 'The Breakfast Club', year: 1985 },
      { title: 'Vicky Cristina Barcelona', year: 2008 },
      { title: 'Casino Royale', year: 2006 },
      { title: 'The Dreamers', year: 2003 },
      { title: 'He Died with a Felafel in His Hand', year: 2001 },
      { title: 'Four Rooms', year: 1995 },
    ],
  },
];
