import type { Metadata } from 'next';

import { Recursive } from 'next/font/google';
import './globals.css';
import NeonCursor from '@/components/NeonCursor';

const recursive = Recursive({
  variable: '--font-recursive',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${recursive.variable}  antialiased`}>
        {children}
        <div className='min-[320px]:hidden sm:block'>
          <NeonCursor />
        </div>
      </body>
    </html>
  );
}
